FoodMania/Controllers/StockController.cs
using Dblayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FoodMania.Models;

namespace FoodMania.Controllers
{
    public class StockController : Controller
    {

        FoodManiaEntities Db = new FoodManiaEntities();
        // GET: Stock
        public ActionResult StockItemCategory(int? id)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            var stockcategories = new CRU__StockItemCategoryMV(id);
            ViewBag.VisibleStatusID = new SelectList(Db.VisibleStatusTables.ToList(), "VisibleStatusID", "VisibleStatus", stockcategories.VisibleStatusID);
            return View(stockcategories);
        }

        [HttpPost]
        public ActionResult StockItemCategory(CRU__StockItemCategoryMV stockcategory)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }

            int userid = 0;
            int.TryParse(Convert.ToString(Session["UserID"]), out userid);
            stockcategory.CreatedBy_UserID = userid;
            if (ModelState.IsValid)
            {
                if (stockcategory.StockItemCategoryID == 0)
                {
                    var checkexist = Db.StockItemCategoryTables.Where(s => s.StockItemCategory.Trim().ToUpper() == stockcategory.StockItemCategory.Trim().ToUpper()).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var newcategory = new StockItemCategoryTable();
                        newcategory.StockItemCategory = stockcategory.StockItemCategory;
                        newcategory.VisibleStatusID = stockcategory.VisibleStatusID;
                        newcategory.CreatedBy_UserID = userid;
                        Db.StockItemCategoryTables.Add(newcategory);
                        Db.SaveChanges();
                        return RedirectToAction("StockItemCategory", new { id = 0 });
                    }

                    else
                    {
                        ModelState.AddModelError("StockItemCategory", "Already Registered");
                    }
                }
                else
                {
                    var checkexist = Db.StockItemCategoryTables.Where(s => s.StockItemCategory.Trim().ToUpper() == stockcategory.StockItemCategory.Trim().ToUpper() && s.StockItemCategoryID != stockcategory.StockItemCategoryID).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var editcategory = Db.StockItemCategoryTables.Find(stockcategory.StockItemCategoryID);
                        editcategory.StockItemCategory = stockcategory.StockItemCategory;
                        editcategory.VisibleStatusID = stockcategory.VisibleStatusID;
                        editcategory.CreatedBy_UserID = userid;
                        Db.Entry(editcategory).State = System.Data.Entity.EntityState.Modified;
                        Db.SaveChanges();
                        return RedirectToAction("StockItemCategory", new { id = 0 });
                    }

                    else
                    {
                        ModelState.AddModelError("StockItemCategory", "Already Registered");
                    }

                }
            }


            ViewBag.VisibleStatusID = new SelectList(Db.VisibleStatusTables.ToList(), "VisibleStatusID", "VisibleStatus", stockcategory.VisibleStatusID);
            return View(stockcategory);
        }

        public ActionResult OrderType(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            var ordertype = new CRU__OrderTypeMV(id);
            return View(ordertype);

        }

        [HttpPost]
        public ActionResult OrderType(CRU__OrderTypeMV orderTypeMV)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                if (orderTypeMV.OrderTypeID == 0)
                {
                    var checkexist = Db.OrderTypeTables.Where(o => o.OrderType.Trim().ToUpper() == orderTypeMV.OrderType.Trim().ToUpper()).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var newordertype = new OrderTypeTable();
                        newordertype.OrderType = orderTypeMV.OrderType;
                        Db.OrderTypeTables.Add(newordertype);
                        Db.SaveChanges();
                        return RedirectToAction("OrderType", new { id = 0 });
                    }
                    else
                    {
                        ModelState.AddModelError("OrderType", "Already Exist!");
                    }
                }
                else
                {
                    var checkexist = Db.OrderTypeTables.Where(o => o.OrderType.Trim().ToUpper() == orderTypeMV.OrderType.Trim().ToUpper() && o.OrderTypeID != orderTypeMV.OrderTypeID).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var editordertype = Db.OrderTypeTables.Find(orderTypeMV.OrderTypeID);
                        editordertype.OrderType = orderTypeMV.OrderType;
                        Db.Entry(editordertype).State = System.Data.Entity.EntityState.Modified;
                        Db.SaveChanges();
                        return RedirectToAction("OrderType", new { id = 0 });
                    }
                    else
                    {
                        ModelState.AddModelError("OrderType", "Already Exist!");
                    }
                }
            }
            return View(orderTypeMV);
        }


        public ActionResult StockMenuCategory(int? id)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            var menucategories = new CRU_StockMenuCategoryMV(id);

            return View(menucategories);
        }


        [HttpPost]
        public ActionResult StockMenuCategory(CRU_StockMenuCategoryMV menucategory)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }

            int userid = 0;
            int.TryParse(Convert.ToString(Session["UserID"]), out userid);
            menucategory.CreatedBy_User = userid;
            if (ModelState.IsValid)
            {
                if (menucategory.StockMenuCategoryID == 0)
                {
                    var checkexist = Db.StockMenuCategoryTables.Where(s => s.StockMenuCategory.Trim().ToUpper() == menucategory.StockMenuCategory.Trim().ToUpper()).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var newcategory = new StockMenuCategoryTable();
                        newcategory.StockMenuCategory = menucategory.StockMenuCategory;

                        newcategory.CreatedBy_User = userid;
                        Db.StockMenuCategoryTables.Add(newcategory);
                        Db.SaveChanges();
                        return RedirectToAction("StockMenuCategory", new { id = 0 });
                    }

                    else
                    {
                        ModelState.AddModelError("StockMenuCategory", "Already Registered");
                    }
                }
                else
                {
                    var checkexist = Db.StockMenuCategoryTables.Where(s => s.StockMenuCategory.Trim().ToUpper() == menucategory.StockMenuCategory.Trim().ToUpper() && s.StockMenuCategoryID != menucategory.StockMenuCategoryID).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var editcategory = Db.StockMenuCategoryTables.Find(menucategory.StockMenuCategoryID);
                        editcategory.StockMenuCategory = menucategory.StockMenuCategory;

                        editcategory.CreatedBy_User = userid;
                        Db.Entry(editcategory).State = System.Data.Entity.EntityState.Modified;
                        Db.SaveChanges();
                        return RedirectToAction("StockMenuCategory", new { id = 0 });
                    }

                    else
                    {
                        ModelState.AddModelError("StockMenuCategory", "Already Registered");
                    }

                }
            }



            return View(menucategory);
        }

        public ActionResult StockItem(int? id)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            var stockitem = new CRU_StockItemMV(id);
            ViewBag.StockItemCategoryID = new SelectList(Db.StockItemCategoryTables.ToList(), "StockItemCategoryID", "StockItemCategory", stockitem.StockItemCategoryID);
            ViewBag.VisibleStatusID = new SelectList(Db.VisibleStatusTables.ToList(), "VisibleStatusID", "VisibleStatus", stockitem.VisibleStatusID);
            ViewBag.OrderTypeID = new SelectList(Db.OrderTypeTables.ToList(), "OrderTypeID ", "OrderType", stockitem.OrderTypeID);
            return View(stockitem);
        }




        [HttpPost]
        public ActionResult StockItem(CRU_StockItemMV cru_StockItemMV)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");

FoodMania/Views/Stock/OrderType.cshtml
@model FoodMania.Models.CRU__OrderTypeMV
@{
    ViewBag.Title = "Order Types";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>Order Types</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/Stock/OrderType")">Order Types</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>Order Types</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->

            <div class="col-md-5 col-12">
                <!--  user type form Start  -->
                @using (Html.BeginForm("OrderType", "Stock", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.OrderTypeID)
                    <div class="form-group row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <i class="icofont icofont-ui-user"></i>
                            @Html.EditorFor(model => model.OrderType, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Order Type" } })
                            @Html.ValidationMessageFor(model => model.OrderType, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="buttons">
                        @if (Model.OrderTypeID == 0)
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Create" />
                        }
                        else
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Update" />
                        }
                    </div>
                }
                <!--  user type form End  -->
            </div>
            <div class="col-md-7 col-12">
                <!--  List Start  -->
                <div class="table-responsive-md">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td class="text-center">
                                   Order Type
                                </td>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Lists)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.OrderType)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "OrderType", new { id = item.OrderTypeID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!--  List End  -->
            </div>
        </div>
    </div>
</div>

FoodMania/Views/Stock/StockDeal.cshtml
@model FoodMania.Models.CRU_StockDealMV
@{
    ViewBag.Title = "Deals";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>Deals</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/Stock/StockDeal")">Deals</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>Deals</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->

            <div class="col-md-12 col-12">
                <!--  user type form Start  -->
                @using (Html.BeginForm("StockDeal", "Stock", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.StockDealID)
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    Deal Title :
                                    @Html.EditorFor(model => model.StockDealTitle, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Deal Title" } })
                                    @Html.ValidationMessageFor(model => model.StockDealTitle, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    Deal Price :
                                    @Html.EditorFor(model => model.DealPrice, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Deal Price" } })
                                    @Html.ValidationMessageFor(model => model.DealPrice, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    Discount :
                                    @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Discount" } })
                                    @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    Select Status :
                                    @Html.DropDownList("VisibleStatusID", null, "--Choose Status--", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.VisibleStatusID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-8 col-sm-8 col-8">
                                        <label style="margin-left:20px;">Upload Deal Photo</label>
                                        <br />
                                        <span class="btn btn-default btn-file">
                                            @Html.TextBoxFor(model => model.PhotoPath, new { @class = "upload-pic form-control-file", @type = "file" })
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-4 col-sm-4 col-4">
                                        <div class="buttons">
                                            @if (Model.StockDealID == 0)
                                            {
                                                <input class="btn btn-theme btn-md btn-wide" type="submit" value="Create" />
                                            }
                                            else
                                            {
                                                <input class="btn btn-theme btn-md btn-wide" type="submit" value="Update" />
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <!--  user type form End  -->
            </div>

        </div>
    </div>
</div>

<div class="menu">
    <div class="menu-inner">
        <div class="container">
            <div class="row ">
                <div class="col-sm-12 col-12 commontop text-center">
                    <h4>Stock Deals</h4>
                    <div class="divider style-1 center">
                        <span class="hr-simple left"></span>
                        <i class="icofont icofont-ui-press hr-icon"></i>
                        <span class="hr-simple right"></span>
                    </div>
                </div>

                <!--  List Start  -->
                <div class="col-sm-12 col-12">
                    <!--  Menu Tabs Content Start  -->
                    <div class="tab-content">
                        <!--  Menu Tab Start  -->
                        <div class="row">
                            @{
                                foreach (var deal in Model.Deals)
                                {
                                    <div class="col-md-6 col-sm-6 col-12">
                                        <!-- Box Start -->
                                        <div class="box">
                                            <div class="image">
                                                <img src="@Url.Content(deal.DealPhoto)" alt="image" title="@deal.StockDealTitle" class="img-fluid" style="width:130px; height:200px; max-width: 100%; height: auto;" />

                                            </div>
                                            <div class="caption">
                                                <h4>@deal.StockDealTitle | Discount: @deal.Discount PKR | Reg-Date : @deal.StockDealRegisterDate.ToString("dd/MM/yyyy") | Start-Date: @deal.StockDealStartDate.ToString("dd/MM/yyyy") | End-Date: @deal.StockDealEndDate.ToString("dd/MM/yyyy") | (@deal.VisibleStatus)</h4>
                                                <p class="des">Deal Items : (@deal.DealItems)</p>
                                                <span>
                                                    @Html.ActionLink("Edit", "StockDeal", new { id = deal.StockDealID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                                    @Html.ActionLink("Add Items", "StockDealItem", new { dealid = deal.StockDealID, stockdealdetailid = 0 }, new { @class = "btn btn-theme btn-md btn-wide" })
                                                </span>
                                                <div class="price">@deal.DealPrice BDT</div>
                                            </div>
                                        </div>
                                        <!-- Box End -->
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FoodMania/Views/Stock/StockDealItem.cshtml
@model FoodMania.Models.CRU_StockDealDetailMV
@{
    ViewBag.Title = "Deal";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>Deal Items</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/Stock/StockDealItem?dealid="+Model.StockDealID+"&stockdealdetailid="+Model.StockDealDetailID+"")">Stock Deal Items</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>Deal Items</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->

            <div class="col-md-12 col-12">
                <!--  user type form Start  -->
                @using (Html.BeginForm("StockDealItem", "Stock", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.StockDealID)
                    @Html.HiddenFor(model => model.StockDealDetailID)
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    Select Item :
                                    @Html.DropDownList("StockItemID", null, "--Choose Item--", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StockItemID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    Enter Quantity :
                                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Deal Price" } })
                                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    Discount :
                                    @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Discount" } })
                                    @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    Select Status :
                                    @Html.DropDownList("VisibleStatusID", null, "--Choose Status--", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.VisibleStatusID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-12">
                                    <div class="buttons">
                                        @if (Model.StockDealDetailID == 0)
                                        {
                                            <input class="btn btn-theme btn-md btn-wide" type="submit" value="Create" />
                                        }
                                        else
                                        {
                                            <input class="btn btn-theme btn-md btn-wide" type="submit" value="Update" />
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <!--  user type form End  -->
            </div>

        </div>
    </div>
</div>

<div class="menu">
    <div class="menu-inner">
        <div class="container">
            <div class="row ">
                <div class="col-sm-12 col-12 commontop text-center">
                    <h4>Deal Items</h4>
                    <div class="divider style-1 center">
                        <span class="hr-simple left"></span>
                        <i class="icofont icofont-ui-press hr-icon"></i>
                        <span class="hr-simple right"></span>
                    </div>
                </div>

                <!--  List Start  -->
                <div class="col-sm-12 col-12">
                    <!--  Menu Tabs Content Start  -->
                    <div class="tab-content">
                        <!--  Menu Tab Start  -->
                        <div class="row">
                            @{
                                foreach (var item in Model.DealItems)
                                {
                                    <div class="col-md-6 col-sm-6 col-12">
                                        <!-- Box Start -->
                                        <div class="box">
                                            <div class="image">
                                                <img src="@Url.Content(item.ItemPhotoPath)" alt="image" title="@item.StockItemTitle" class="img-fluid" style="width:130px; height:200px; max-width: 100%; height: auto;" />

                                            </div>
                                            <div class="caption">
                                                <h4>@item.StockItemTitle | Discount: @item.Discount PKR | (@item.VisibleStatus)</h4>
                                                <p class="des">Quantity : (@item.Quantity) | Order Type : (@item.OrderType)</p>
                                                <span>
                                                    @Html.ActionLink("Edit", "StockDealItem", new { dealid = item.StockDealID, stockdealdetailid = item.StockDealDetailID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                                </span>
                                                <div class="price">@item.ItemSize</div>
                                            </div>
                                        </div>
                                        <!-- Box End -->
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>