FoodMania/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using FoodMania.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dblayer;

namespace FoodMania.Controllers
{
   
    public class SettingController : Controller
    {
        FoodManiaEntities Db = new FoodManiaEntities();
        // GET: Setting
        public ActionResult List_UserTypes(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            var usertype = new CRU_UserTypeMV(id);
            return View(usertype);
        }

        [HttpPost]
        public ActionResult List_UserTypes(CRU_UserTypeMV cRU_UserTypeMV)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                if (cRU_UserTypeMV.UserTypeID == 0)
                {
                    var checkexist = Db.UserTypeTables.Where(u => u.UserType == cRU_UserTypeMV.UserType).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var usertype = new UserTypeTable();
                        usertype.UserType = cRU_UserTypeMV.UserType;
                        Db.UserTypeTables.Add(usertype);
                        Db.SaveChanges();
                        return RedirectToAction("List_UserTypes", new { id = 0 });
                    }
                    else
                    {
                        ModelState.AddModelError("UserType", "All Ready Exist!");
                    }
                }
                else
                {
                    var checkexist = Db.UserTypeTables.Where(u => u.UserType == cRU_UserTypeMV.UserType && u.UserTypeID != cRU_UserTypeMV.UserTypeID).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var usertype = Db.UserTypeTables.Find(cRU_UserTypeMV.UserTypeID);
                        usertype.UserType = cRU_UserTypeMV.UserType;
                        Db.Entry(usertype).State = System.Data.Entity.EntityState.Modified;
                        Db.SaveChanges();
                        return RedirectToAction("List_UserTypes", new { id = 0 });
                    }
                    else
                    {
                        ModelState.AddModelError("UserType", "All Ready Exist!");
                    }
                }
            }
            return View(cRU_UserTypeMV);
        }

        public ActionResult List_Genders(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            var gender = new CRU_GenderMV(id);
            return View(gender);
        }

        [HttpPost]
        public ActionResult List_Genders(CRU_GenderMV cRU_GenderMV)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                if (cRU_GenderMV.GenderID == 0)
                {
                    var checkexist = Db.GenderTables.Where(g => g.GenderTittle == cRU_GenderMV.GenderTitle).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var gender = new GenderTable();
                        gender.GenderTittle = cRU_GenderMV.GenderTitle;
                        Db.GenderTables.Add(gender);
                        Db.SaveChanges();
                        return RedirectToAction("List_Genders", new { id = 0 });
                    }
                    else
                    {
                        ModelState.AddModelError("GenderTitle", "All Ready Exist!");
                    }
                }
                else
                {
                    var checkexist = Db.GenderTables.Where(g => g.GenderTittle == cRU_GenderMV.GenderTitle && g.GenderID != cRU_GenderMV.GenderID).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var editgender = Db.GenderTables.Find(cRU_GenderMV.GenderID);
                        editgender.GenderTittle = cRU_GenderMV.GenderTitle;
                        Db.Entry(editgender).State = System.Data.Entity.EntityState.Modified;
                        Db.SaveChanges();
                        return RedirectToAction("List_Genders", new { id = 0 });
                    }
                    else
                    {
                        ModelState.AddModelError("GenderTitle", "All Ready Exist!");
                    }
                }
            }
            return View(cRU_GenderMV);
        }


        public ActionResult List_UserStatus(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            var userstatus = new CRU_UserStatusMV(id);
            return View(userstatus);
        }

        [HttpPost]
        public ActionResult List_UserStatus(CRU_UserStatusMV cRU_UserStatusMV)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                if (cRU_UserStatusMV.UserStatusID == 0)
                {
                    var checkexist = Db.UserStatusTables.Where(s => s.UserStatus.ToUpper() == cRU_UserStatusMV.UserStatus.ToUpper()).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var userstatus = new UserStatusTable();
                        userstatus.UserStatus = cRU_UserStatusMV.UserStatus;
                        Db.UserStatusTables.Add(userstatus);
                        Db.SaveChanges();
                        return RedirectToAction("List_UserStatus", new { id = 0 });

                    }
                    else
                    {
                        ModelState.AddModelError("UserStatus", "Already Exist");
                    }
                }
                else
                {
                    var checkexist = Db.UserStatusTables.Where(s => s.UserStatus.ToUpper() == cRU_UserStatusMV.UserStatus.ToUpper() && s.UserStatusID != cRU_UserStatusMV.UserStatusID).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var userstatus = Db.UserStatusTables.Find(cRU_UserStatusMV.UserStatusID);
                        userstatus.UserStatus = cRU_UserStatusMV.UserStatus;
                        Db.Entry(userstatus).State = System.Data.Entity.EntityState.Modified;
                        Db.SaveChanges();
                        return RedirectToAction("List_UserStatus", new { id = 0 });

                    }
                    else
                    {
                        ModelState.AddModelError("UserStatus", "Field Required*");
                    }
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Fill All Field Properly.");
            }
            return View(cRU_UserStatusMV);
        }

        public ActionResult List_VisibleStatus(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            var status = new CRU_VisibleStatusMV(id);
            return View(status);
        }

        [HttpPost]
        public ActionResult List_VisibleStatus(CRU_VisibleStatusMV cRU_VisibleStatusMV)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                if (cRU_VisibleStatusMV.VisibleStatusID == 0)
                {
                    var checkexist = Db.VisibleStatusTables.Where(s => s.VisibleStatus.ToUpper() == cRU_VisibleStatusMV.VisibleStatus.ToUpper()).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var status = new VisibleStatusTable();
                        status.VisibleStatus = cRU_VisibleStatusMV.VisibleStatus;
                        Db.VisibleStatusTables.Add(status);
                        Db.SaveChanges();
                        return RedirectToAction("List_VisibleStatus", new { id = 0 });

                    }
                    else
                    {
                        ModelState.AddModelError("VisibleStatus", "Field Required*");
                    }
                }
                else
                {
                    var checkexist = Db.VisibleStatusTables.Where(s => s.VisibleStatus.ToUpper() == cRU_VisibleStatusMV.VisibleStatus.ToUpper() && s.VisibleStatusID != cRU_VisibleStatusMV.VisibleStatusID).FirstOrDefault();
                    if (checkexist == null)
                    {
                        var editstatus = Db.VisibleStatusTables.Find(cRU_VisibleStatusMV.VisibleStatusID);
                        editstatus.VisibleStatus = cRU_VisibleStatusMV.VisibleStatus;
                        Db.Entry(editstatus).State = System.Data.Entity.EntityState.Modified;
                        Db.SaveChanges();
                        return RedirectToAction("List_VisibleStatus", new { id = 0 });

                    }
                    else
                    {
                        ModelState.AddModelError("VisibleStatus", "Field Required*");
                    }
                }
            }
            else
            {

FoodMania/Views/Setting/List_Genders.cshtml
@model FoodMania.Models.CRU_GenderMV
@{
    ViewBag.Title = "Genders";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>Genders</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/Setting/List_Genders")">Genders</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>Genders</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->

            <div class="col-md-5 col-12">
                <!--  user type form Start  -->
                @using (Html.BeginForm("List_Genders", "Setting", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.GenderID)
                    <div class="form-group row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <i class="icofont icofont-ui-user"></i>
                            @Html.EditorFor(model => model.GenderTitle, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Gender" } })
                            @Html.ValidationMessageFor(model => model.GenderTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="buttons">
                        @if (Model.GenderID == 0)
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Create" />
                        }
                        else
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Update" />
                        }
                    </div>
                }
                <!--  user type form End  -->
            </div>
            <div class="col-md-7 col-12">
                <!--  List Start  -->
                <div class="table-responsive-md">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td class="text-center">
                                    @Html.DisplayNameFor(model => model.GenderTitle)
                                </td>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.List_Genders)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GenderTittle)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "List_Genders", new { id = item.GenderID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!--  List End  -->
            </div>
        </div>
    </div>
</div>

FoodMania/Views/Setting/List_UserAddress.cshtml
@model FoodMania.Models.CRU_UserAddressMV
@{
    ViewBag.Title = "User Address";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>User Address</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/Setting/List_UserAddress")">User Address</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>User Addresses</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->

            <div class="col-md-5 col-12">
                <!--  user type form Start  -->
                @using (Html.BeginForm("List_UserAddress", "Setting", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.UserAddressID)
                    <div class="form-group row">
                        <div class="col-md-12 col-sm-12 col-12">
                            @Html.DropDownList("AddressTypeID", null, "--Choose Type--", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.AddressTypeID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <i class="icofont icofont-ui-user"></i>
                            @Html.EditorFor(model => model.FullAddress, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Full Address" } })
                            @Html.ValidationMessageFor(model => model.FullAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12 col-sm-12 col-12">
                            @Html.DropDownList("VisibleStatusID", null, "--Choose Status--", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.VisibleStatusID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="buttons">
                        @if (Model.UserAddressID == 0)
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Create" />
                        }
                        else
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Update" />
                        }
                    </div>
                }
                <!--  user type form End  -->
            </div>
            <div class="col-md-7 col-12">
                <!--  List Start  -->
                <div class="table-responsive-md">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td class="text-center">
                                    Address Type
                                </td>
                                <td class="text-center">
                                    Full Address
                                </td>
                                <td class="text-center">
                                    Status
                                </td>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.List)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AddressType)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FullAddress)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.VisibleStatus)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "List_UserAddress", new { id = item.UserAddressID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!--  List End  -->
            </div>
        </div>
    </div>
</div>

FoodMania/Views/Setting/List_UserStatus.cshtml
@model FoodMania.Models.CRU_UserStatusMV
@{
    ViewBag.Title = "Account Status";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>Account Status</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/Setting/List_UserStatus")">Account Status</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>Account Status</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->

            <div class="col-md-5 col-12">
                <!--  user type form Start  -->
                @using (Html.BeginForm("List_UserStatus", "Setting", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.UserStatusID)
                    <div class="form-group row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <i class="icofont icofont-ui-user"></i>
                            @Html.EditorFor(model => model.UserStatus, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Account Status" } })
                            @Html.ValidationMessageFor(model => model.UserStatus, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="buttons">
                        @if (Model.UserStatusID == 0)
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Create" />
                        }
                        else
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Update" />
                        }
                    </div>
                }
                <!--  user type form End  -->
            </div>
            <div class="col-md-7 col-12">
                <!--  List Start  -->
                <div class="table-responsive-md">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td class="text-center">
                                    @Html.DisplayNameFor(model => model.UserStatusID)
                                </td>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.List_UserStatuses)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserStatus)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "List_UserStatus", new { id = item.UserStatusID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!--  List End  -->
            </div>
        </div>
    </div>
</div>

FoodMania/Views/Setting/List_UserTypes.cshtml
@model FoodMania.Models.CRU_UserTypeMV
@{
    ViewBag.Title = "User Types";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>User Types</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/Setting/List_UserTypes")">User Types</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>User Types</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->

            <div class="col-md-5 col-12">
                <!--  user type form Start  -->
                @using (Html.BeginForm("List_UserTypes", "Setting", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.UserTypeID)
                    <div class="form-group row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <i class="icofont icofont-ui-user"></i>
                            @Html.EditorFor(model => model.UserType, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter User Type" } })
                            @Html.ValidationMessageFor(model => model.UserType, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="buttons">
                        @if (Model.UserTypeID == 0)
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Create" />
                        }
                        else
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Update" />
                        }
                    </div>
                }
                <!--  user type form End  -->
            </div>
            <div class="col-md-7 col-12">
                <!--  List Start  -->
                <div class="table-responsive-md">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td class="text-center">
                                    @Html.DisplayNameFor(model => model.UserType)
                                </td>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.List_UserTypes)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserType)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "List_UserTypes", new { id = item.UserTypeID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!--  List End  -->
            </div>
        </div>
    </div>
</div>

FoodMania/Views/Setting/List_VisibleStatus.cshtml
@model FoodMania.Models.CRU_VisibleStatusMV
@{
    ViewBag.Title = "Visible Status";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>Record Visible Status</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/Setting/List_VisibleStatus")">Record Visible Status</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>Record Visible Status</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->

            <div class="col-md-5 col-12">
                <!--  user type form Start  -->
                @using (Html.BeginForm("List_VisibleStatus", "Setting", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.VisibleStatusID)
                    <div class="form-group row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <i class="icofont icofont-ui-user"></i>
                            @Html.EditorFor(model => model.VisibleStatus, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Record Visible Status Title" } })
                            @Html.ValidationMessageFor(model => model.VisibleStatus, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="buttons">
                        @if (Model.VisibleStatusID == 0)
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Create" />
                        }
                        else
                        {
                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Update" />
                        }
                    </div>
                }
                <!--  user type form End  -->
            </div>
            <div class="col-md-7 col-12">
                <!--  List Start  -->
                <div class="table-responsive-md">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td class="text-center">
                                    @Html.DisplayNameFor(model => model.VisibleStatus)
                                </td>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.List_VisibleStatus)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.VisibleStatus)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "List_VisibleStatus", new { id = item.VisibleStatusID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!--  List End  -->
            </div>
        </div>
    </div>
</div>