FoodMania/Controllers/TableReservationController.cs
using Dblayer;
using FoodMania.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodMania.Controllers
{
    public class TableReservationController : Controller
    {
        // GET: TableReservation
        FoodManiaEntities db = new FoodManiaEntities();


        public ActionResult BookingTables(int id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            int userid = 0;
            int usertypeid = 0;
            int.TryParse(Convert.ToString(Session["UserID"]), out userid);
            int.TryParse(Convert.ToString(Session["UserTypeID"]), out usertypeid);
            var list = new CRU_TableReservationMV(usertypeid, userid, id);
            ViewBag.BookingStatusID = new SelectList(db.BookingStatusTables.ToList(), "BookingStatusID", "BookingStatus", "0");
            return View(list);
        }

        [HttpPost]
        public ActionResult BookingTables(CRU_TableReservationMV cRU_TableReservationMV)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            int userid = 0;
            int.TryParse(Convert.ToString(Session["UserID"]), out userid);
            if (ModelState.IsValid)
            {
                var date = Convert.ToDateTime(cRU_TableReservationMV.ReservationDate).Date.ToString("yyyy/MM/dd");
                var time = cRU_TableReservationMV.ReservationTime;
                var reservationdatetime = Convert.ToDateTime(date + " " + time);
                var reservation = db.BookingTblTables.Find(cRU_TableReservationMV.BookingTableID);
                reservation.ProcessBy_UserID = userid;
                reservation.BookingStatusID = cRU_TableReservationMV.BookingStatusID;
                reservation.Description = cRU_TableReservationMV.Description;
                db.Entry(reservation).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("BookingTables", new { id = 0 });
            }
            return View(cRU_TableReservationMV);
        }


        public ActionResult CancelBooking(int bookingtableid)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            int userid = 0;
            int.TryParse(Convert.ToString(Session["UserID"]), out userid);
            if (ModelState.IsValid)
            {
                var reservation = db.BookingTblTables.Find(bookingtableid);
                reservation.Description = "Canceled By User";
                reservation.BookingStatusID = 4;
                reservation.ProcessBy_UserID = userid;
                db.Entry(reservation).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("BookingTables", new { id = 0 });
            }
            return View();
        }


        [HttpPost]
        public ActionResult BookTable(CRU_TableReservationMV cRU_TableReservationMV)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserTypeID"])))
            {
                return RedirectToAction("Index", "Home");
            }
            int userid = 0;
            int.TryParse(Convert.ToString(Session["UserID"]), out userid);
            if (ModelState.IsValid)
            {
                var date = Convert.ToDateTime(cRU_TableReservationMV.ReservationDate).Date.ToString("yyyy/MM/dd");
                var time = cRU_TableReservationMV.ReservationTime;
                var reservationdatetime = Convert.ToDateTime(date + " " + time);
                var reservation = new BookingTblTable();
                reservation.BookingUserID = userid;
                reservation.FullName = cRU_TableReservationMV.FullName;
                reservation.EmailAddress = cRU_TableReservationMV.EmailAddress;
                reservation.MobileNo = cRU_TableReservationMV.MobileNo;
                reservation.BookingDate = DateTime.Now;
                reservation.ReservationDateTime = reservationdatetime;
                reservation.NoOfPersons = (int)cRU_TableReservationMV.NoOfPersons;
                reservation.ProcessBy_UserID = 0;
                reservation.BookingStatusID = 1;
                reservation.Description = string.Empty;
                db.BookingTblTables.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(cRU_TableReservationMV);
        }
    }

}

FoodMania/Views/TableReservation/BookingTables.cshtml
@model FoodMania.Models.CRU_TableReservationMV
@{
    ViewBag.Title = "Table Reservation";
}
<!-- Breadcrumb Start -->
<div class="bread-crumb">
    <div class="container">
        <div class="matter">
            <h2>Table Reservation</h2>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="@Url.Content("~/Home/Index")">HOME</a></li>
                <li class="list-inline-item"><a href="@Url.Content("~/TableReservation/BookingTables")">Table Reservation</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<div class="contactus">
    <div class="container">
        <div class="row">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop text-center">
                <h4>Table Reservation</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
            </div>
            <!-- Title Content End -->
            @{
                int userid = 0;
                int usertypeid = 0;
                int.TryParse(Convert.ToString(Session["UserID"]), out userid);
                int.TryParse(Convert.ToString(Session["UserTypeID"]), out usertypeid);
                if (usertypeid == 1 || usertypeid == 2 || usertypeid == 3)
                {
                    if (Model.BookingTableID > 0)
                    {
                        <div class="col-md-12 col-12">
                            <!-- form Start  -->
                            @using (Html.BeginForm("BookingTables", "TableReservation", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.BookingTableID)
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-12">
                                                Full Name :
                                                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "name" } })
                                                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-12">
                                                Mobile No :
                                                @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Contact No" } })
                                                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-12">
                                                Reservation Date :
                                                @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "Reservation Date" } })
                                                @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-12">
                                                Reservation Time
                                                @Html.EditorFor(model => model.ReservationTime, new { htmlAttributes = new { @class = "form-control", @placeholder = "Reservation Time" } })
                                                @Html.ValidationMessageFor(model => model.ReservationTime, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-12">
                                                Enter Message :
                                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Message Here" } })
                                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-12">
                                                Process To :
                                                @Html.DropDownList("BookingStatusID", null, "--Choose Type--", htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.BookingStatusID, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="buttons">
                                            <input class="btn btn-theme btn-md btn-wide" style="float:right;" type="submit" value="Process" />
                                        </div>
                                    </div>
                                </div>
                            }
                            <!-- form End  -->
                        </div>
                    }
                }
                <div class="col-md-12 col-12">
                    <!--  List Start  -->
                    <div class="table-responsive-md">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        Status
                                    </th>
                                    <th class="text-center">
                                        Full Name
                                    </th>
                                    <th class="text-center">
                                        Mobile No
                                    </th>
                                    <th class="text-center">
                                        Booking Date
                                    </th>
                                    <th class="text-center">
                                        Reservation Date Time
                                    </th>
                                    <th class="text-center">
                                        No Of Persons
                                    </th>
                                    <th class="text-center">
                                        Description
                                    </th>
                                    <th class="text-center">
                                        Process By
                                    </th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.ReservationList)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.BookingStatus)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FullName) (@Html.DisplayFor(modelItem => item.BookingUserName))
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.MobileNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.BookingDate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ReservationDateTime)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NoOfPersons)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ProcessBy_User)
                                        </td>
                                        <td>
                                            @if (usertypeid == 1 || usertypeid == 2 || usertypeid == 3)
                                            {
                                                @Html.ActionLink("Process", "BookingTables", new { id = item.BookingTableID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                            }
                                            else
                                            {
                                                if (string.IsNullOrEmpty(item.ProcessBy_User))
                                                {
                                                    @Html.ActionLink("Cancel", "CancelBooking", new { bookingtableid = item.BookingTableID }, new { @class = "btn btn-theme btn-md btn-wide" })
                                                }
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!--  List End  -->
                </div>
            }
        </div>
    </div>
</div>
<!--  Reservation End -->

FoodMania/Views/TableReservation/Partial_TableReservation.cshtml
@model FoodMania.Models.CRU_TableReservationMV
<!-- Reservation Start -->
<div class="reservation" id="reservationtable">
    <div class="container">
        <div class="row ">
            <!-- Title Content Start -->
            <div class="col-sm-12 commontop white text-center">
                <h4>Book Your Table</h4>
                <div class="divider style-1 center">
                    <span class="hr-simple left"></span>
                    <i class="icofont icofont-ui-press hr-icon"></i>
                    <span class="hr-simple right"></span>
                </div>
                <p>Decide on a date and time: Choose the date and time you want to visit the restaurant, keeping in mind the restaurant's peak hours and availability.</p>
            </div>
            <!-- Title Content End -->
            <div class="col-md-12 col-12">
                <!-- Reservation Form Start -->
                @using (Html.BeginForm("BookTable", "TableReservation", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "row reservation-form", novalidate = "novalidate" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.BookingTableID)
                    <div class="form-group col-md-4 col-sm-6">
                        <i class="icofont icofont-ui-user"></i>
                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "name" } })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4 col-sm-6">
                        <i class="icofont icofont-ui-message"></i>
                        @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control", @placeholder = "email" } })
                        @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4 col-sm-6">
                        <i class="icofont icofont-phone"></i>
                        @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "mobile number" } })
                        @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4 col-sm-6">
                        <i class="icofont icofont-ui-calendar"></i>
                        @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "booking date (yyyy/mm/dd)" } })
                        @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4 col-sm-6">
                        <i class="icofont icofont-clock-time"></i>
                        @Html.EditorFor(model => model.ReservationTime, new { htmlAttributes = new { @class = "form-control", @placeholder = "booking time (hh:mm AM|PM)" } })
                        @Html.ValidationMessageFor(model => model.ReservationTime, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4 col-sm-6">
                        <i class="icofont icofont-users"></i>
                        @Html.EditorFor(model => model.NoOfPersons, new { htmlAttributes = new { @class = "form-control", @placeholder = "number of persons" } })
                        @Html.ValidationMessageFor(model => model.NoOfPersons, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-12 col-md-12">
                        <div class="">
                            <div id="emailSend" class="alert alert-success" role="alert" style="display: none;">
                                <div class="success-text">Your Message has been successfully sent.</div>
                            </div>
                            <div id="emailError" class="alert alert-danger" role="alert" style="display: none;">
                                <div class="alert-text">Server error <br> Try again later.</div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-12 col-md-12">
                        <div class="text-center">
                            <button type="submit" class="btn btn-theme btn-wide">book now</button>
                        </div>
                    </div>

                }
                <!-- Reservation Form End -->
            </div>
        </div>
    </div>
</div>
<!-- Reservation End  -->